# Generated by Django 5.0.7 on 2024-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service/'),
        ),
    ]
