# Generated by Django 5.0.7 on 2024-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_heading', models.CharField(max_length=250)),
                ('learn_title', models.CharField(max_length=250)),
                ('learn_desc', models.TextField()),
                ('learn_read_link', models.CharField(max_length=400)),
            ],
        ),
    ]
