# Generated by Django 5.0.7 on 2024-10-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_icon', models.CharField(max_length=250)),
                ('our_title', models.CharField(max_length=250)),
                ('our_desc', models.TextField()),
                ('our_img', models.FileField(default=None, max_length=250, null=True, upload_to='service/')),
            ],
        ),
    ]
