# Generated by Django 5.0.7 on 2024-11-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pri_title', models.CharField(max_length=250)),
                ('our_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('person', models.CharField(max_length=150)),
            ],
        ),
    ]
