# Generated by Django 5.0.7 on 2024-12-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_pricing_tablebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
