# Generated by Django 5.0.7 on 2024-12-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_delete_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='our_img',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='service/'),
        ),
    ]
