# Generated by Django 5.0.7 on 2025-09-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
