# Generated by Django 5.0.7 on 2025-09-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourservices',
            old_name='our_icon',
            new_name='our_read_link',
        ),
    ]
