# Generated by Django 5.0.7 on 2025-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_rename_our_icon_ourservices_our_read_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OpenHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_range', models.CharField(max_length=50)),
                ('time_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
    ]
