# Generated by Django 5.0.7 on 2025-09-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_contactinfo_openhour_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='service/'),
        ),
    ]
