# Generated by Django 5.0.7 on 2025-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='service/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
    ]
