# Generated by Django 5.0.7 on 2025-09-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_order_address_order_mobile_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
